### ISSUE TITLE
(v5) Use hash indexes for hash values

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-db#104]
Jonathan made a really good point about using hash indexes instead of btree indexes for our columns that store hashes... since they are already hashes and we won't ever be using the (<, <=, >, >=) operators on them.

The only issue with hash indexes is that they require resizing, which involves recalculating the entire index once they exceed some initial capacity. This can take a really long time, and can also cause issues (locking, deadlocks) with concurrent operations.

This would have been a major concern for the v3 schema since table (index) size was essentially unbound, but for the v4 and v5 schemas where we have and never exceed a known partition size we should be able to set things up such that the hash indexes never need to be resized.

**Comment by i-norden** [comment]
Actually there *are* potentially cases where we want to use one of those comparison operators or other properties of the btree index, for example if we want to collect all the state/storage leaf keys that share some prefix/are all along a certain path. Btree indexes can be used during prefix searches, hash indexes ofc cannot be used like this. 

For this reason I am hesitant to change the index on state and storage leaf keys (the places where the hashes are used as key in a trie and so it could be useful to do path/prefix scans). For the various trie root hashes, transaction hashes, and block hashes I think it is fine though. I also see no problem with using hash indexes on all our indexed `address` types, can't think of any time it would be useful to be able to order or prefix scan those.

**Comment by i-norden** [comment]
Also worth mentioning that hash indexes can't be multi-column and cannot be unique.

**Comment by dboreham** [comment]
$0.02/wo: My historical experience (plus some advice from people more familiar with the problem domain) has been that the negative properties of hash index methods (wide distribution of insert cost due to bucket overflow; hard to reason about whether to keep a page in primary or secondary storage) usually outweigh the benefits. Therefore, I've always used B-tree even if ordered traversal is not needed.

**Comment by i-norden** [comment]
I agree, also can't index null values in hash indexes (afaik) so that is problematic for a few of the fields that were otherwise potential candidates.
