### ISSUE TITLE
Add or update existing graphQL trigger/notify to support subscription RPC endpoints in ipld-eth-server

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-db#119]
In ipld-eth-server we would like to support eth json rpc endpoints that are dependent on a live header stream, such as those dependent on the [GasPriceOracle](https://github.com/ethereum/go-ethereum/blob/master/eth/gasprice/gasprice.go#L59) e.g. https://github.com/cerc-io/ipld-eth-server/issues/213.

This could be accomplished with a new pg_notify function and trigger, or by updating the [existing ones](https://github.com/cerc-io/ipld-eth-db/blob/v4/db/migrations/00015_create_postgraphile_triggers.sql#L50) to emit the required fields (current one could be used, but would would require making a second trip to the database with that blockhash to collect the rest of the required information).

I need to check with @ashwinphatak whether or not these existing triggers are still being used after the switch away from postgraphile to our [custom graphQL server](https://github.com/cerc-io/ipld-eth-server/tree/v4/pkg/graphql).

**Comment by ashwinphatak** [comment]
@i-norden the triggers aren't being used now. Or to put it another way, we didn't need to port over any subscription endpoints as the watchers use a pull based approach.

**Comment by i-norden** [comment]
@ashwinphatak thank you!
