### ISSUE TITLE
Add back CI tests

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-db#121]
We used to have github action triggers for running jobs to

1. Check that all the UP migrations run successfully
2. Check that the final schema after running all migrations matches the updated schema.sql commited in the PR
3. Check that running UP and then DOWN all the migrations goes without error

They were commented out at some point: https://github.com/cerc-io/ipld-eth-db/blob/v4/.github/workflows/on-pr.yaml#L21
Because of the timescaleDB-related migrations breaking things in CI.

We should circle back and fix this at some point.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-db/issues/1
