### ISSUE TITLE
Consider removing IPLDization of logs

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-db#144]
Internalize the logs data field into `eth.log_cids`. Rename `eth.log_cids` to `eth.logs`. Drop the `cid` column. Will remove some data redundancy that currently exists between `eth.log_cids` and `ipld.blocks`. As far I as I know, there is no need to reference or lookup individual logs by CID or expose them over IPFS in this capacity. Individual logs are never hashed into any of the canonical data structures, they exist within a list within a receipt (which is hashed into the receipt trie). This will involve making corresponding changes across the indexing software and ipld-eth-server, so is probably very low priority as the payoff for the amount of work required is low.

**Comment by telackey** [comment]
https://git.vdb.to/cerc-io/ipld-eth-db/issues/3
