### ISSUE TITLE
Consider hash indexes for log_data and tx_data

### ISSUE THREAD

**Issue by i-norden** [vulcanize/ipld-eth-db#61]
These columns can (and do) exceed the size limit for btree indexes so we can't apply them, but we could apply a hash index. Hash indexes don't enable any search operation except equivalency, but this would be fine for these values since the other comparison operators aren't all that useful for these arbitrary byte arrays (e.g. <=, >=).

Related is https://github.com/vulcanize/ipld-eth-db/issues/28.

**Comment by AFDudley** [comment]
Are these columns still too large for a btree index within a shard?

**Comment by i-norden** [comment]
Too large to index with btree in any context

**Comment by i-norden** [comment]
Per Jonathon's recent comments, we should also revisit using hash indexes for for all hash values in our tables.
